repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy src
        language: system
        pass_filenames: false
      - id: check-story-docs
        name: check-story-docs
        entry: python scripts/check_story_docs.py
        language: system
        pass_filenames: false
