"""Column mapping constants for COFEPRIS BRSDM."""

EXPECTED_COLUMNS: tuple[str, ...] = (
    "numero_de_registro",
    "denominacion_distintiva",
    "fecha_expedicion_vigencia",
    "fecha_expedicion_vigencia_prorroga",
    "estado",
    "forma_farmaceutica",
    "indicaciones_terapeuticas",
    "contra_indicaciones",
    "vida_util",
    "fraccion",
    "denominacion_generica",
    "vista_administracion",
    "tipo_medicamento",
    "presentacion",
    "cantidad",
    "sistema_organico",
    "grupo_farmacologico",
    "subgrupo_farmacologico",
    "subgrupo_quimico",
    "sustancia_quimica",
    "titular",
    "domicilio",
    "fabricantes_medicamentos",
    "fabricantes_farmacos",
    "acondicionado_por",
    "acondicionado_extranjero",
    "distribuidores",
    "unidad_farmaco_vigilancia",
    "fecha_emision",
)
